# searchStr 可缩写为 org, replaceStr 可缩写为 rep (译前和译后字典同样适用)

gptDict = [
    # 语义标注

    { org = "[title]", rep = "[title]", note = "场景标题标记，请保留，标记的该行文本是整个场景（后续对话）的标题，非角色对话或旁白" },
    { org = "[select]", rep = "[select]", note = "选项文本标记，请保留，标记的该行是玩家可选择的选项条目，非角色对话或旁白，通常出现在分支节点处" },

    { org = "$o", rep = "$o", note = "游戏文本分隔符，请保留" },
    { org = "-", rep = "-", note = "游戏文本特殊符号，请保留" },
    { org = "@", rep = "@", note = "游戏文本特殊符号，请保留" },
    { org = "/", rep = "/", note = "游戏文本特殊符号，请保留" },
    { org = "$", rep = "$", note = "游戏文本特殊指令，后面跟着一系列字母和数字，请保留" },

    # 主要角色

    { org = "$s1", rep = "$s1", note = "游戏占位符，人名，男性，主人公，全名为“$s0$s1”，高中生，天涯孤独的贫困学生，父母双亡，由祖父抚养长大，祖父去世后投靠远亲菖蒲，直率、有些懒散、怕麻烦、容易动感情但嘴硬，拥有“非时”（トキジク）的特质" },
    { org = "$s0", rep = "$s0", note = "游戏占位符，姓氏，男性，主人公的姓氏，全名为“$s0$s1”，或者也代指主人公的祖先" },
    { org = "$s0$s1", rep = "$s0$s1", note = "游戏占位符，人名全名，男性，主人公的全名" },
    { org = "$s1クン", rep = "$s1君", note = "人名，男性，主人公“$s1”的称呼" },
    { org = "$s1くん", rep = "$s1君", note = "人名，男性，主人公“$s1”的称呼" },
    { org = "$s1ちゃん", rep = "小$s1", note = "人名，男性，主人公“$s1”的称呼" },
    { org = "お兄ちゃん", rep = "哥哥", note = "人名，男性，菊里对主人公“$s1”的称呼" },
    { org = "$s1さん", rep = "$s1同学", note = "人名，男性，主人公“$s1”的称呼" },
    { org = "ツバメ", rep = "燕子", note = "源自《幸福王子》中的燕子，咲耶将其投影为主人公“$s1”" },


    { org = "菊里", rep = "菊里", note = "人名，女，全名“比良坂菊里”（比良坂 菊里，ひらさか くくり），初中/高中生，天姫神社的巫女之一，比主人公、咲耶、椿等人小，活泼、开朗、有些冒失、天真烂漫" },
    { org = "比良坂菊里", rep = "比良坂菊里", note = "人名全名，女，即“菊里”" },
    { org = "比良坂", rep = "比良坂", note = "人名姓氏，菊里的姓氏" },
    { org = "菊里ちゃん", rep = "小菊里", note = "人名，女性，菊里的称呼" },


    { org = "あやめ", rep = "菖蒲", note = "人名，女，全名“御巫菖蒲”（御巫 あやめ，みかなぎ あやめ），外表25到30左右，主人公“$s1”的远亲，天姫神社的代理宫司，学园的古文老师，开朗、天然、有些脱线、爱喝酒的大姐姐（里剧情：实际上为了追求不老不死，利用主人公，已经活了千年以上，椿的母亲（通过归魂术，非亲女儿），“御巫”一族的当主）" },
    { org = "御巫あやめ", rep = "御巫菖蒲", note = "人名全名，女，即“菖蒲”" },
    { org = "あやめさん", rep = "菖蒲姐", note = "人名，女，菖蒲的称呼" },
    { org = "あやめ先生", rep = "菖蒲老师", note = "人名，女，菖蒲的称呼" },
    { org = "おねーさん", rep = "姐姐", note = "人名，女，菖蒲的自称" },
    { org = "母さま", rep = "母亲大人", note = "人名，女，椿对菖蒲的称呼（里剧情）" },


    { org = "咲耶", rep = "咲耶", note = "人名，女，全名“御巫咲耶”（御巫 咲耶，みかなぎ さくや），高中生，主人公的同班同学，天姫神社的巫女之一，菖蒲的侄女，傲娇、易怒、纯情，容易害羞、暴力倾向，拥有“分魂”能力" },
    { org = "御巫咲耶", rep = "御巫咲耶", note = "人名全名，女，即“咲耶”" },
    { org = "サクヤ", rep = "御巫咲耶", note = "人名，女性，咲耶的称呼" },
    { org = "咲耶ちゃん", rep = "小咲耶", note = "人名，女性，咲耶的称呼" },
    { org = "咲耶おねーちゃん", rep = "咲耶姐姐", note = "人名，女性，咲耶的称呼" },

    { org = "御巫さん", rep = "御巫同学", note = "人名，女性，咲耶的称呼（如果上下文代指咲耶）" },

    { org = "ミカナギ", rep = "御巫", note = "人名姓氏，菖蒲和咲耶的姓氏" },
    { org = "御巫", rep = "御巫", note = "人名姓氏，菖蒲和咲耶的姓氏，也代指家族，天女后裔" },

    { org = "美月", rep = "美月", note = "人名，女，全名“中条美月”（中条 美月，なかじょう みつき），高中生，主人公的同班同学兼青梅竹马，活泼、强势、多管闲事、直率、有些霸道、" },
    { org = "中条美月", rep = "中条美月", note = "人名全名，女，即“美月”" },
    { org = "中条", rep = "中条", note = "人名姓氏，美月的姓氏" },
    { org = "ミッちゃん", rep = "小美", note = "人名，女性，美月的称呼" },
    { org = "中条さん", rep = "中条同学", note = "人名，女性，美月的称呼" },


    { org = "椿", rep = "椿", note = "人名，女，全名“橘椿”（橘 椿，たちばな つばき），高中生，主人公的同班同学，天姫神社的巫女之一，无表情、冷静、毒舌、难以捉摸、喜欢奇怪的事物（里剧情：不死之身，实际1000岁以上）" },
    { org = "橘椿", rep = "橘椿", note = "人名全名，女，即“椿”" },
    { org = "橘", rep = "橘", note = "人名姓氏，椿的姓氏" },
    { org = "椿ちゃん", rep = "小椿", note = "人名，女性，椿的称呼" },
    { org = "椿おねーちゃん", rep = "椿姐姐", note = "人名，女性，椿的称呼" },
    { org = "ツバキ", rep = "椿", note = "人名，女性，对椿在黄泉的半身的称呼，椿是留在现世的另一半" },
    { org = "タチバナ", rep = "橘", note = "人名，女性，椿的姓氏的片假名写法" },
    { org = "沙羅", rep = "沙罗", note = "人名，女性，椿被囚禁在黄泉的一半魂，椿则是留在现世的另一半魂" },

    { org = "神崎恵", rep = "神崎惠", note = "人名全名，男，即“神崎”" },
    { org = "神崎", rep = "神崎", note = "人名姓氏，惠的姓氏，全名“神崎惠”（神崎 恵，かんざき けい），历史教师，民俗学知识丰富，主人公们的班主任，拥有驱魔镜和神秘知识（里剧情：实为主人公家先祖、不老不死者，有千年仇恨、最终选择帮助主人公）" },
    { org = "神崎先生", rep = "神崎老师", note = "人名，男性" },

    { org = "広", rep = "广", note = "人名，男，全名“须藤广”（須藤 広，すどう ひろし），高中生，主人公的同班同学，明的好友，身材矮小，戴眼镜，极度热情、话多、行动派、重度巫女控" },
    { org = "須藤広", rep = "须藤广", note = "人名全名，男，即“广”" },
    { org = "須藤", rep = "须藤", note = "人名姓氏，广的姓氏" },
    { org = "ヒロシ", rep = "广", note = "人名，男性，即“广”（広）" },
    { org = "メガネ", rep = "眼镜", note = "人名，男性，主人公对广的称呼" },
    { org = "広くん", rep = "广君", note = "人名，男性，广的称呼" },


    { org = "明", rep = "明", note = "人名，男，全名“高里明”（高里 明，たかざと あきら），高中生，主人公的同班同学，广的好友，稳重、温和、善于照顾人、对朋友宽容" },
    { org = "高里明", rep = "高里明", note = "人名全名，男，即“明”" },
    { org = "高里", rep = "高里", note = "人名姓氏，明的姓氏" },
    { org = "アキラ", rep = "明", note = "人名，男性，即“明”" },
    { org = "明くん", rep = "明君", note = "人名，男性，明的称呼" },


    { org = "爺ちゃん", rep = "爷爷", note = "人名，男性，已故，主人公的祖父，严格的剑道师父，将主人公养育成人" },


    # 其他术语/角色

    { org = "巫女ファンクラブ", rep = "巫女粉丝俱乐部", note = "组织名，广和明的组织" },

    { org = "天姫神社", rep = "天姬神社", note = "地名，主人公居住的神社，菖蒲担任代理宫司，故事主要舞台" },
    { org = "天姫ノ舞", rep = "天姬之舞", note = "技能/仪式，舞蹈名称" },

    { org = "神隠し", rep = "神隐", note = "人被神秘力量带走失踪的现象，本作核心谜团" },
    { org = "常世", rep = "常世", note = "特殊概念，死者之国，异世界，与“现世”相对" },
    { org = "常世国", rep = "常世国", note = "特殊概念，传说中的国度，死者之国，异世界" },
    { org = "黄泉路", rep = "黄泉路", note = "地名，通往黄泉的道路" },
    { org = "黄泉", rep = "黄泉", note = "特殊概念，死者之国，与现世相对的异世界" },

    { org = "トキジク", rep = "非时", note = "专有名词/特殊词汇，不老不死之力，主人公的灵魂本质，或者指超越时间规律的存在" },
    { org = "非時香果", rep = "非时香果", note = "传说中能赋予不老不死的神秘果实" },
    { org = "不老不死", rep = "不老不死", note = "吃下非时香果后获得的状态" },

    { org = "天女の呪い", rep = "天女的诅咒", note = "主人公家继承的诅咒，与御巫家系联姻的代价" },
    { org = "天女", rep = "天女", note = "御巫家族的祖先，从天降临的女性" },

    { org = "お面の男", rep = "狐面男", note = "人名代称，男性，神秘人物，多次帮助主人公" },

    { org = "分魂", rep = "分魂", note = "特殊设定，将生命/寿命分给他人的特殊能力" },
    { org = "亡者", rep = "亡者", note = "特殊存在，死者的灵魂，会附身于人" },

    { org = "儀式", rep = "仪式", note = "神社进行的某种仪式" },

    { org = "お守り", rep = "护符", note = "具有驱魔力量的护身符，多次成为关键道具" },

    { org = "宮司", rep = "宫司", note = "神社的最高负责人" },
    { org = "巫女", rep = "巫女", note = "神社的女性神职人员，咲耶、椿、菊里的身份" },

    { org = "水垢離", rep = "瀑布修行", note = "神道教的禊祓仪式，在瀑布下冲淋以清净身心" },

    { org = "華月", rep = "华月", note = "招牌/家名，美月家的拥有二百年历史的老字号料亭" },

    { org = "ワラ人形", rep = "稻草人偶", note = "稻草人偶，替身/依代，椿给予主人公" },

    { org = "エターナルヴァージン", rep = "Eternal virgin", note = "特殊称号/词汇" },
    { org = "スタッフロール", rep = "Staff Roll", note = "制作人员名单" },

    { org = "ヌシ", rep = "主子", note = "狗的名字，雄性，老犬，聪明、忠诚、有灵性" },

    { org = "オスカー・ワイルド", rep = "奥斯卡·王尔德", note = "人名，男性，作家" },
    { org = "シェークスピア", rep = "莎士比亚", note = "人名，男性" },
    { org = "ロミオ", rep = "罗密欧", note = "人名，男性" },
    { org = "ジュリエット", rep = "朱丽叶", note = "人名，女性" },

    { org = "幸福の王子様", rep = "幸福王子", note = "奥斯卡·王尔德童话，咲耶的自我投射与理想" },

    { org = "道人", rep = "道人", note = "人名，男性，幽灵，死亡时20岁，菊里的亲哥哥，极端妹控、嫉妒心强、自私、死后仍执着于妹妹" },
    { org = "ミカちゃん", rep = "小美香", note = "人名，女性，山崎的昵称" },
    { org = "山崎", rep = "山崎", note = "人名，女性" },
]
